
server:
  port: 7000
  tomcat:
    connection-timeout: 18000000
    max-connections: 18000000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qiaqia?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 'ljl123123@G'

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      #上传单个文件大小
      maxFileSize: 100MB
      #总上传文件大小
      maxRequestSize: 1000MB

  mail:
    host: smtp.qq.com
    username: 858810078@qq.com
    password: jdwxhvnywvdvbbef
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

qiaqia:
  key: qifen
  path: /home/qifen/mysoft/qiaqia

